site_name: Мой Справочник

theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Включить темную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Включить светлую тему
  
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - header.autohide
    - navigation.header
    - navigation.instant

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  # --- ВОТ ЭТОТ БЛОК ВОЗВРАЩАЕТ И НАСТРАИВАЕТ ПОДСВЕТКУ КОДА: ---
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

plugins:
  - search

extra_css:
  - stylesheets/extra.css

nav:
  - 'Home': index.md
  - 'Code':
      - 'Last': Code/last.md
      - 'Substr Extract': Code/Substr_Extract.md
      - 'Create Table': Code/creat_table.md
  - 'Da spk':
      - 'Viele Werte in einer Feld': da_spk/viele_werte_in_einer_feld.md
      - 'Neue Auftrag Schritten': da_spk/neue_auftrag_schritten.md
      - 'Import Anleitung': da_spk/import_anleitung.md
      - 'Export Tabelle': da_spk/export_tabelle_zur_kollegen.md
      - 'Antworten Entwurf': da_spk/antworten_entwurf.md
  - 'Sys admin':
      - 'Meldung Bewegung': sys_admin/meldung_bewegung.md
  - 'Wortschatz':
      - 'Основные слова': wortschatz/основные_слова.md
      - 'Test': wortschatz/test.md
  - 'Zeit': Zeit/rechner.md  